<a href="https://colab.research.google.com/github/azrapatvi/nlp_practice/blob/main/15_language_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [31]:
df=pd.read_csv('https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Machine%20Learning%2BNLP%20Project%20Language%20Detection/language.csv')

df.head()

,Text,language
0,klement gottwaldi surnukeha palsameeriti ning paigutati mausoleumi surnukeha oli aga liiga hilja ja oskamatult palsameeritud ning hakkas ilmutama lagunemise tundemärke aastal viidi ta surnukeha mausoleumist ära ja kremeeriti zlíni linn kandis aastatel – nime gottwaldov ukrainas harkivi oblastis kandis zmiivi linn aastatel – nime gotvald,Estonian
1,sebes joseph pereira thomas på eng the jesuits and the sino-russian treaty of nerchinsk the diary of thomas pereira bibliotheca instituti historici s i -- rome libris,Swedish
2,ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เริ่มตั้งแต่ถนนสนามไชยถึงแม่น้ำเจ้าพระยาที่ถนนตก กรุงเทพมหานคร เป็นถนนรุ่นแรกที่ใช้เทคนิคการสร้างแบบตะวันตก ปัจจุบันผ่านพื้นที่เขตพระนคร เขตป้อมปราบศัตรูพ่าย เขตสัมพันธวงศ์ เขตบางรัก เขตสาทร และเขตบางคอแหลม,Thai
3,"விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திரிகை-விசாகப்பட்டின ஆசிரியர் சம்பத்துடன் இணைந்து விரிவுபடுத்தினார் ஆண்டுகள் தொடர்ந்து செயலராக இருந்து தமிழ்மன்றத்தை நடத்திச் சென்றார் கோவை செம்மொழி மாநாட்டில் ""தமிழ்ச்சங்கங்களும் தமிழும்"" எனும் தலைப்பில் பிற மாநிலங்களில் தமிழ்வளர்ச்சி பற்றி கட்டுரை வாசித்தார்",Tamil
4,de spons behoort tot het geslacht haliclona en behoort tot de familie chalinidae de wetenschappelijke naam van de soort werd voor het eerst geldig gepubliceerd in door kudelin,Dutch

In [32]:
df.isnull().sum()

Text        0
language    0
dtype: int64

In [33]:
df.duplicated().sum()

np.int64(141)

In [34]:
df.shape

(22000, 2)

In [35]:
pd.set_option('display.max_colwidth', None)

In [36]:
df[df["Text"].duplicated(keep=False)].sort_values("Text")

,Text,language
12915,ईसा पूर्व ईसा मसीह के जन्म से पूर्व के वर्षों को दर्शाता है। ईसा के जन्म को अधार मानकर उसके जन्म से ईसा पूर्व या वर्ष पूर्व के वर्ष को इस प्रकार प्रदर्शित किया जाता है। यह जूलियन कलेण्डर पर अधारित एक सामूहिक वर्ष माना जाता है। अधिकांश विश्व में इसी पद्धति के आधार पर पुराने वर्षों की गणना की जाती है। भारत में इसके अलावा कई पंचाग प्रसिद्ध है जैसे विक्रम संवत जो ईसा के जन्म से या वर्ष पूर्व शुरु होती है। इसके अलावा शक संवत भी प्रसिद्ध है। शक संवत भारत का प्राचीन संवत है जो ईसा के जन्म के वर्ष बाद से आरम्भ होता है। शक संवत भारत का राष्ट्रीय कैलेंडर है।,Hindi
6404,ईसा पूर्व ईसा मसीह के जन्म से पूर्व के वर्षों को दर्शाता है। ईसा के जन्म को अधार मानकर उसके जन्म से ईसा पूर्व या वर्ष पूर्व के वर्ष को इस प्रकार प्रदर्शित किया जाता है। यह जूलियन कलेण्डर पर अधारित एक सामूहिक वर्ष माना जाता है। अधिकांश विश्व में इसी पद्धति के आधार पर पुराने वर्षों की गणना की जाती है। भारत में इसके अलावा कई पंचाग प्रसिद्ध है जैसे विक्रम संवत जो ईसा के जन्म से या वर्ष पूर्व शुरु होती है। इसके अलावा शक संवत भी प्रसिद्ध है। शक संवत भारत का प्राचीन संवत है जो ईसा के जन्म के वर्ष बाद से आरम्भ होता है। शक संवत भारत का राष्ट्रीय कैलेंडर है।,Hindi
1846,ईसा पूर्व ईसा मसीह के जन्म से पूर्व के वर्षों को दर्शाता है। ईसा के जन्म को अधार मानकर उसके जन्म से ईसा पूर्व या वर्ष पूर्व के वर्ष को इस प्रकार प्रदर्शित किया जाता है। यह जूलियन कलेण्डर पर अधारित एक सामूहिक वर्ष माना जाता है। अधिकांश विश्व में इसी पद्धति के आधार पर पुराने वर्षों की गणना की जाती है। भारत में इसके अलावा कई पंचाग प्रसिद्ध है जैसे विक्रम संवत जो ईसा के जन्म से या वर्ष पूर्व शुरु होती है। इसके अलावा शक संवत भी प्रसिद्ध है। शक संवत भारत का प्राचीन संवत है जो ईसा के जन्म के वर्ष बाद से आरम्भ होता है। शक संवत भारत का राष्ट्रीय कैलेंडर है।,Hindi
13141,ईसा पूर्व ईसा मसीह के जन्म से पूर्व के वर्षों को दर्शाता है। ईसा के जन्म को अधार मानकर उसके जन्म से ईसा पूर्व या वर्ष पूर्व के वर्ष को इस प्रकार प्रदर्शित किया जाता है। यह जूलियन कलेण्डर पर अधारित एक सामूहिक वर्ष माना जाता है। अधिकांश विश्व में इसी पद्धति के आधार पर पुराने वर्षों की गणना की जाती है। भारत में इसके अलावा कई पंचाग प्रसिद्ध है जैसे विक्रम संवत जो ईसा के जन्म से या वर्ष पूर्व शुरु होती है। इसके अलावा शक संवत भी प्रसिद्ध है। शक संवत भारत का प्राचीन संवत है जो ईसा के जन्म के वर्ष बाद से आरम्भ होता है। शक संवत भारत का राष्ट्रीय कैलेंडर है।,Hindi
7244,ईसा पूर्व ईसा मसीह के जन्म से पूर्व के वर्षों को दर्शाता है। ईसा के जन्म को अधार मानकर उसके जन्म से ईसा पूर्व या वर्ष पूर्व के वर्ष को इस प्रकार प्रदर्शित किया जाता है। यह जूलियन कलेण्डर पर अधारित एक सामूहिक वर्ष माना जाता है। अधिकांश विश्व में इसी पद्धति के आधार पर पुराने वर्षों की गणना की जाती है। भारत में इसके अलावा कई पंचाग प्रसिद्ध है जैसे विक्रम संवत जो ईसा के जन्म से या वर्ष पूर्व शुरु होती है। इसके अलावा शक संवत भी प्रसिद्ध है। शक संवत भारत का प्राचीन संवत है जो ईसा के जन्म के वर्ष बाद से आरम्भ होता है। शक संवत भारत का राष्ट्रीय कैलेंडर है।,Hindi
...,...,...
14499,இக்கோயில் முதன்மைத் திருக்கோயில் என்ற வகைப்பாட்டில் இந்து அறநிலையத்துறையின் கட்டுப்பாட்டில் உள்ளது பரம்பரை அல்லாத அறங்காவலர் அமைப்பால் நிர்வகிக்கப்படுகிறது,Tamil
8478,இக்கோயில் முதன்மைத் திருக்கோயில் என்ற வகைப்பாட்டில் இந்து அறநிலையத்துறையின் கட்டுப்பாட்டில் உள்ளது பரம்பரை அல்லாத அறங்காவலர் அமைப்பால் நிர்வகிக்கப்படுகிறது,Tamil
8222,"இவ்வூர் கடல்மட்டத்தில் இருந்து சராசரியாக மீட்டர் உயரத்தில் இருக்கிறது இவ்வூரின் அமைவிடம் °""n °""eஆகும் இங்கு குடும்பங்களும் மக்களும் வசிக்கின்றனர் இதில் ஆண்களும் பெண்களும் அடங்குவர்",Tamil
21739,"இவ்வூர் கடல்மட்டத்தில் இருந்து சராசரியாக மீட்டர் உயரத்தில் இருக்கிறது இவ்வூரின் அமைவிடம் °""n °""eஆகும் இங்கு குடும்பங்களும் மக்களும் வசிக்கின்றனர் இதில் ஆண்களும் பெண்களும் அடங்குவர்",Tamil
17905,"இவ்வூர் கடல்மட்டத்தில் இருந்து சராசரியாக மீட்டர் உயரத்தில் இருக்கிறது இவ்வூரின் அமைவிடம் °""n °""eஆகும் இங்கு குடும்பங்களும் மக்களும் வசிக்கின்றனர் இதில் ஆண்களும் பெண்களும் அடங்குவர்",Tamil

In [37]:
df[df["Text"].duplicated(keep=False)] # markk all duplicated values as tru includeing ofirst occuernece as well without thiss will show duplicated second value onylyy with this u will get all duplicatess including first occuerences too

,Text,language
166,"bisby fa roskov yr orrell tm nicolson d paglinawan le bailly n kirk pm bourgoin t baillargeon g ouvrard d red ""species itis catalogue of life annual checklist"" species reading uk diakses pada september",Indonesian
209,inlandsklimat råder i trakten årsmedeltemperaturen i trakten är °c den varmaste månaden är augusti då medeltemperaturen är °c och den kallaste är februari med - °c,Swedish
220,تاثيرات ئي پنسلينونه ورته دي داسيدو په مقابل کى مقاوم دي او دخولى دلاري ښه جذبيږي په خالى ګيډه په خاصه توګه غوښه خوړونکو حيواناتو ته ورکول جذب ئي بهتره دي دacred او دهغه دهمکارانو په واسطه چه کومه تجربه په موږکانو باندي په کال کى ترسره شوي وو ښکاره کوي چه amoxacilline نسبت ampicilline ته په ګرام منفى باسيلونو باندي زيات تاثير لري ampiclox - دغه دوا په شيدوخوړونکو حيواناتو کى دecoli په انتاناتو کى ترينه استفاده کيږي او همدارنګه mg ampicilline او mg cloxacilline په مخلوطى شکل دنباتى تيلو سره يوځاي او شيدوخوړونکو حيواناتو دتيونو په التهاباتو کى ترينه استفاده کوي,Pushto
410,"bisby fa roskov yr orrell tm nicolson d paglinawan le bailly n kirk pm bourgoin t baillargeon g ouvrard d red ""species itis catalogue of life annual checklist"" species reading uk diakses pada september",Indonesian
440,aastakümned aastad aastad aastad aastad aastad - aastad - aastad aastad aastad aastad aastad,Estonian
...,...,...
21427,seperti asteroid secara keseluruhan asteroid ini terbentuk dari nebula matahari primordial sebagai pecahan planetisimal sesuatu di nebula matahari muda yang tidak cukup besar untuk berubah menjadi planet,Indonesian
21440,كباقي كويكبات معسكر الإغريق يقع مداره في النقطة l من نقاط لاغرانج وفق نظام الشمس - المشتري يبلغ القدر المطلق لهذا الكويكب ونصف المحور الرئيسي لمداره وحدة فلكية وقد تم رصده مرة حتى شباطفبراير الإشارة المرجعية له وفق الملحق الدوري لمدارات الكويكبات هي mpo‏,Arabic
21667,خواص - نسبتا اسيدي خواص لري په اوبو کى منحل دي داسيدو په مقابل کى مقاومت لري نو همداوجه دي چه دخولى دلارى استعماليږي pharmacodynamic - فارمکوديناميک ئي دپنسلين په شان دي pharmacokenitic - دخولى دلارى تطبيق که څه هم نظر حيوان ته فرق کوي خوجذب ئي مکمل او دوه ساعته وروسته خپل غلظت اعظمى حدته رسوي که دتطبيق اندازه دوچنده ته ورسيږي نو په وينه کى به ئي هم غلظت دوچنده شى په صحرائى موږکانو کى دکلمو په لومړي برخه کى جذب کيږي دجذب څخه وروسته دبدن ټولو برخو ته جذبيږي ځکه پښتورګو کى غلظت نسبتا لوړ خوشوکى نخاع ته په کمه اندازه سره توزيع کيږي ميتابوليزم ئي نه ترسره کيږي او په فعال شکل سره دبدن څخه وځى غلظت ئي په صفراکى دوينى په پرتله چنده لوړ دي نوهمداوجه دي چه دهمدي لادي په انفکشنونو کى کار کله تري اخلى ددي ترڅنګ درحم او پلاسيتا ته ښه تيريږي اطراح ئي دپښتورګو او صفرادلاري ترسره کيږي دتطپيق څخه وروسته - ساعته په دوران کى دصفرا دلارى ښکاره کيږي دتاثير ساحه - په ګرام مثبتو او منفى دواړو باکترياوو تاثير لري چه پدي اساس دالاندي باکترياوي ورسره حساس شميرل کيږي streptococcus staphylococcus coryno bacterium fucalis ecoli fusi fumis kati bacilla pratus pastrolla clostridium shagilla salmonella brocella اوهغه باکترياوي چه pencilliase توليدوي لکه stap,Pushto
21739,"இவ்வூர் கடல்மட்டத்தில் இருந்து சராசரியாக மீட்டர் உயரத்தில் இருக்கிறது இவ்வூரின் அமைவிடம் °""n °""eஆகும் இங்கு குடும்பங்களும் மக்களும் வசிக்கின்றனர் இதில் ஆண்களும் பெண்களும் அடங்குவர்",Tamil
21743,haec commentatio automatice praeparata res astronomicas colligit excerptas e pagina [] sitús small-body database quem elaboraverunt nasa et jpl apud institutum technologiae californiense,Latin

In [38]:
df.drop_duplicates(inplace=True)

In [39]:
df.shape

(21859, 2)

In [41]:
df.columns=df.columns.str.lower()

In [43]:
X=df['text']
y=df['language']

In [44]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42,stratify=y)

In [45]:
X_train

20092                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        en el primer piso de esta gran casa vive la dueña tsa tsa coca guazzini junto a su único hijo cristián cristián gaete un joven con síndrome de down el departamento del segundo piso es ocupado por anita amparo noguera una joven estudiante de teatro que verá en uno de los jóvenes músicos al amor de su vida
14748                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      继首部《蜘蛛侠》获得成功后，邓斯特又出演了年的续集《蜘蛛侠》。该片也获得了影评人的良好评价，商业上同样大获成功，创下了北美上映首周的电影票房新纪录，是年的世界电影票房亚军，收入超过亿美元。同年她又在浪漫喜剧《温布尔登》中扮演一位打入温布尔登网球锦标赛的网球新星，与保羅·彼特尼扮演的一个事业正逐渐走下坡路的球手陷入情网。该片获得的评价褒贬不一，但多位影评人都称赞了邓斯特的表现。《今日美国》的克劳迪娅·普格（claudia puig）认为邓斯特和彼特尼之间有强劲的化学反应，邓斯特真实可信地塑造了一个时髦而自信的球员。
5484                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    இக்கோயில் தொகுப்புக் கோயில் என்ற வகைப்பாட்டில் இந்து அறநிலையத்துறையின் கட்டுப்பாட்டில் உள்ளது பரம்பரை அல்லாத அறங்காவலர் அமைப்பால் நிர்வகிக்கப்படுகிறது
21357                        कॉफी उगाने का एक लम्बा इतिहास है जो पहले इथोपिया से इसके बाद अरेबिया से जुड़ा है यह येमेन से भी काफी सम्बन्ध रखता है। हालांकि पेरिस में बिबलियोथेक नेशनेल के अनुसार इसका सबसे पुराना इतिहास  ई पूर्व का है। इसका मूल स्रोत एब्बिसिनिया में भी पाया गया है जहां से इसे  वीं शताब्दी में अरेबिया लाया गया। भारतीय सन्दर्भ एक भारतीय मुस्लिम संत बाबा बुदान से शुरू हुआ जब मक्का की एक तीर्थयात्रा पर सात कॉफ़ी बीन्स को तस्करी के द्वारा येमेन से भारत के मैसूर में लाया गया। इन्हें वह अपनी कमर पर बांध कर लाया था इन्हें चंद्रगिरी की पहाड़ियों में उगाया गया  मीटर  फीट अब इन्हें चिक्कामगलुरु जिले में बाबा बुदान गिरी के नाम से जाना जाता है। यह नाम उसी संत के नाम पर पड़ा गिरी का अर्थ है "पहाड़ी" कॉफ़ी के हरे बीजों को अरब से बहार लेजाना गैर-कानूनी माना जाता था। क्योंकि सात नंबर को इस्लाम में एक पवित्र नंबर माना जाता है इसलिए संत के द्वारा सात कॉफ़ी के बीजों को ले जाया जाना एक धार्मिक कार्य माना गया। यह भारत में कॉफी उद्योग की शुरुआत थी और विशेष रूप से मैसूर के तत्कालीन राज्य में जो वर्तमान में कर्नाटक राज्य का एक हिस्सा है। इसे बाबा बुदान की बहादुरी की उपलब्धि थी क्योंकि अरब में अन्य देशों को कॉफ़ी के निर्यात पर सख्ती से रोक लगायी गयी थी इसे केवल भुन कर या उबाल
10922                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   أول فيلم روائي طويل هو مدرسة للأوغاد شاركت في البطولة في عام  فيلم التلال لديها عيون الجزء الثاني في عام  ولعبت دور كلير في طبعة جديدة من بروم نايت كما أنها ظهرت في فيلم بروكن حيث كان قي الفيلم قبلة مع هيذر غراهام وشاركت في وقت لاحق مع النجم الذي شاركها بطولة بروم نايت إدريس إلبا في فيلم عيد الميلاد هذا العام
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ...
12065                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        另一方面，近年來世界上有些國家也意識到可再生能源的重要性，而大力鼓吹，特別是在風電方面，風電從年來即每年有的成長速度，至年全球裝機容量已達 gw。另外就個別國家而言：例如德國：再生能源發電從年占全部發電量約，發展至年底的 ，其中為風電；是生物質能發電， 是水力，太陽光電有，有萬的就業人口。
9607                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          azur ve asmar fransızca azur et asmar daha önce en ünlü filmi kirikou et la sorcière filmini yapan uzun metraj bir michel ocelot animasyon filmi
1187                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 توجه به گذشتهٔ انسان به طور طبیعی باعث تقسیم زمان به تکه‌های قابل اداره شده‌است راه‌های زیادی برای تقسیم گذشته وجود دارد که از این میان می‌توان به تقسیم‌های تاریخ‌شماری فرهنگی و موضوعی اشاره کرد این سه گونهٔ تقسیم‌بندی انحصاری نیستند و غالباً می‌توان موارد تداخل را بین آن‌ها مشاهده کرد تمرکز روی مکان زمان یا موضوعی خاص بین موّرخان امری عادی است و باعث تخصص‌گرایی در تاریخ‌نگاری می‌شود تاریخ برای دیگران به شکل اصطلاحی کلی به معنای مطالعهٔ هر چیز دربارهٔ انسان‌های پیشین درآمده‌است اما به تازگی حتی این محدوده هم توسط رشته‌هایی چون تاریخ بزرگ به چالش کشیده می‌شود از روزگاران گذشته تاریخ را با هدف‌های عملی یا نظری می‌خواندند اما امروزه آن را از جهت کنجکاوی فکری هم مطالعه می‌کنند
6621                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            کلاوک بین الاقوامی ہوائی اڈا یورپ کے ملک آئس لینڈکے شہرreykjavkمیں واقع ہے۔کلاوک بین الاقوامی ہوائی اڈہکےجس صوبے میں واقع ہے اس کانام[[southern peninsu{{la]]۔
19902    roads untraveled amerikalı rock grubu olan linkin parkın  stüdyo albümü living thingsteki  sırada bulunan şarkısı şarkı albümdeki en yavaş ritimlere sahip ve en sakin şarkıdır sözleri tamamen saflık  iyilik  dostluk ve barış mesajları verir sözleri grubun solist ve geri vokalisti olan chester bennington ve mike shinoda tarafından yazılmıştır ayrıca şarkının en dikkat çeken özelliklerinden biri de  nakarattan sonra elektro gitar yerine akustik gitar kullanılmasıdır grubun geri vokal ve gitaristi mike shinoda bbcye verdiği röportajında tüm şarkıları genel olarak değerlendirirken roads untraveled şarkısı için şunları demiştir  " yapabilirdik tüm şarkıları sert gitar ritimlerinden oluşturabilirdik bunun yanında vokal kısımlarını da screamler ile süsleyebilirdik ama bunların modası çoktan geçti artık nu-metal dinlenmiyor heavy metalde sadece bazı kesimlere hitap ediyor bizim amacımız belirli bir dinleyici grubuna özel şarkılar yapmak değil bizim amacımız den e herkesin ilgi ile dinleyebileceği evrensel ve anlamlı şarkılar yapmak bunun için roads untraveled şarkısı kimsenin başını ağrıtmayacak şekilde dizayn edildi hafif ritimler yakalayıcı nakaratlar ve soft g
Name: text, Length: 16394, dtype: object

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer()

In [47]:
X_train=tfidf.fit_transform(X_train)
X_test=tfidf.transform(X_test)

In [51]:
from sklearn.naive_bayes import MultinomialNB

model_without_weights=MultinomialNB()

In [52]:
model_without_weights

MultinomialNB()

In [53]:
model_without_weights.fit(X_train,y_train)

MultinomialNB()

In [54]:
y_pred=model_without_weights.predict(X_test)

y_pred

array(['Swedish', 'French', 'Portugese', ..., 'Romanian', 'Dutch', 'Thai'],
      dtype='<U10')

In [55]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.9568161024702653

In [56]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()

In [68]:
from sklearn.utils.class_weight import compute_sample_weight

sample_weights=compute_sample_weight(
    class_weight='balanced',
    y=y_train
)

In [69]:
model.fit(X_train, y_train, sample_weight=sample_weights)

MultinomialNB()

In [70]:
y_pred=model.predict(X_test)

y_pred

array(['Swedish', 'French', 'Portugese', ..., 'Romanian', 'Dutch', 'Thai'],
      dtype='<U10')

In [71]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,y_pred))

0.9423604757548033

In [73]:
new_text = ["आज मौसम बहुत अच्छा है और मैं अपने दोस्तों के साथ बाहर जा रहा हूँ।"]

new_text_tfidf = tfidf.transform(new_text)

prediction = model.predict(new_text_tfidf)

print(prediction)

['Hindi']

In [42]:
df.head(2)

,text,language
0,klement gottwaldi surnukeha palsameeriti ning paigutati mausoleumi surnukeha oli aga liiga hilja ja oskamatult palsameeritud ning hakkas ilmutama lagunemise tundemärke aastal viidi ta surnukeha mausoleumist ära ja kremeeriti zlíni linn kandis aastatel – nime gottwaldov ukrainas harkivi oblastis kandis zmiivi linn aastatel – nime gotvald,Estonian
1,sebes joseph pereira thomas på eng the jesuits and the sino-russian treaty of nerchinsk the diary of thomas pereira bibliotheca instituti historici s i -- rome libris,Swedish